import { searchEverything, recentMessages, stats, listEvents, listLinks } from '../core/db.js';
import { formatDate, truncate, tsMs } from '../core/format.js';
export function globalStats(){return stats();}
export function chatAnalytics(jid){const rows=recentMessages(jid,10000);if(!rows.length)return null;const byHour=Array(24).fill(0),types={};let first=Infinity,last=0;const words=new Map();for(const r of rows){const d=new Date(tsMs(r.ts));const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Sao_Paulo',hour:'2-digit',hour12:false}).format(d));byHour[hour%24]++;types[r.type]=(types[r.type]||0)+1;first=Math.min(first,r.ts);last=Math.max(last,r.ts);for(const w of String(r.text||'').toLowerCase().match(/[\p{L}\p{N}]{4,}/gu)||[])words.set(w,(words.get(w)||0)+1);}return{total:rows.length,first,last,byHour,types,topWords:[...words].sort((a,b)=>b[1]-a[1]).slice(0,15),peak:byHour.map((count,h)=>({h,count})).sort((a,b)=>b.count-a.count).slice(0,8)};}
export function isUnusualHour(jid,hour){const a=chatAnalytics(jid);if(!a||a.total<30)return false;const nonzero=a.byHour.filter(Boolean);const avg=nonzero.length?nonzero.reduce((a,b)=>a+b,0)/nonzero.length:0;return (a.byHour[hour]||0)===0&&avg>=2;}
export function formatAnalytics(jid,a){if(!a)return '📊 Não há dados suficientes neste chat.';const types=Object.entries(a.types).sort((x,y)=>y[1]-x[1]).slice(0,8).map(([k,v])=>`${k}:${v}`).join(' · ');return`📊 *ANALYTICS*\n💬 ${jid}\nMensagens: *${a.total}*\nPrimeira: ${formatDate(a.first)}\nÚltima: ${formatDate(a.last)}\n🔥 Picos: ${a.peak.map(x=>`${x.h}h (${x.count})`).join(', ')}\n📦 Tipos: ${types||'—'}\n🔤 Palavras frequentes: ${a.topWords.map(([w])=>w).join(', ')||'—'}`;}
export function find(q,limit=40){const r=searchEverything(q,limit);const out=[];for(const x of r.messages)out.push(`💬 *MENSAGEM*\n🕒 ${formatDate(x.ts)} • ${x.from_me?'EU':x.sender_name||'?'}\n${truncate(x.text||`[${x.type||'mídia'}]`,220)}\n📍 ${x.remote_jid}\n🆔 ${x.message_id}`);for(const x of r.links)out.push(`🔗 *LINK*\n🕒 ${formatDate(x.ts)}\n${truncate(x.url,300)}\n📍 ${x.remote_jid}`);for(const x of r.media)out.push(`💾 *MÍDIA* #${x.id}\n🕒 ${formatDate(x.created_at)}\n${x.kind} • ${x.bytes} B\n📍 ${x.remote_jid}`);for(const x of r.events)out.push(`📡 *EVENTO*\n🕒 ${formatDate(x.ts)}\n${x.kind}\n📍 ${x.remote_jid||'—'}\n${truncate(x.data_json||'',220)}`);return out.slice(0,Math.min(120,limit*3)).join('\n\n');}
export function eventText(kind,limit=40){const rows=listEvents(kind,limit);return rows.map(r=>`🕒 ${formatDate(r.ts)} • ${r.kind}\n${r.remote_jid||''}${r.ref_id?` / ${r.ref_id}`:''}\n${truncate(r.data_json||'',350)}`).join('\n\n');}
export function linkText(limit=40){return listLinks(limit).map(r=>`🔗 ${r.url}\n🕒 ${formatDate(r.ts)}\n💬 ${r.remote_jid}`).join('\n\n');}
