import { savePresence, saveReceipt, saveReaction, saveCall, saveEvent, getWatch } from '../core/db.js';
import { isFeatureOn } from '../core/features.js';
import { ownerJid, isOwnerJid } from '../core/identity.js';
import { formatDate, senderName, extractText, card, chatKind } from '../core/format.js';
const num=j=>String(j||'').split('@')[0].split(':')[0];
const who=j=>{const w=getWatch(j);return w?.label&&w.label!==num(j)?`${w.label} (${num(j)})`:num(j);};
import { watched, settings } from './watch.js';

const cooldown=new Map();
function okCooldown(k,ms=30000){const now=Date.now();const last=cooldown.get(k)||0;if(now-last<ms)return false;cooldown.set(k,now);return true;}
async function shouldWatch(jid){if(watched(jid))return true;return false;}

export async function onReaction(sock,msg){if(!isFeatureOn('reaction'))return;
  const r=msg?.message?.reactionMessage;if(!r?.key?.id)return;const actor=msg.key.participant||msg.key.remoteJid;saveReaction({remoteJid:msg.key.remoteJid,messageId:r.key.id,actorJid:actor,emoji:r.text||'',ts:Date.now()});saveEvent({kind:'reaction',remoteJid:msg.key.remoteJid,refId:r.key.id,data:{actor,emoji:r.text||''}});
  const targetOwn=r.key.fromMe===true||isOwnerJid(sock,r.key.participant);if(!targetOwn&&!await shouldWatch(msg.key.remoteJid))return;if(!okCooldown(`reaction::${msg.key.remoteJid}::${r.key.id}::${actor}::${r.text}`))return;
  await sock.sendMessage(ownerJid(sock),{text:card('💬 *REAÇÃO*',[`👤 ${senderName(msg)}`,`💬 ${chatKind(msg.key.remoteJid)} · ${num(msg.key.remoteJid)}`,`${r.text||'↩️ (removeu a reação)'}`,`🕒 ${formatDate(Date.now())}`])}).catch(()=>{});
}
export async function onPresence(sock,ev){if(!isFeatureOn('presence'))return;
  if(!ev?.presences)return;for(const [jid,info] of Object.entries(ev.presences)){if(!(await shouldWatch(jid)))continue;const status=info?.lastKnownPresence||info?.presence||'unknown';savePresence({jid,status,ts:Date.now()});saveEvent({kind:'presence',remoteJid:jid,data:{status}});if(!okCooldown(`presence::${jid}::${status}`,45000))continue;await sock.sendMessage(ownerJid(sock),{text:card('📡 *PRESENÇA*',[`👤 ${who(jid)}`,`Status: *${status}*`,`🕒 ${formatDate(Date.now())}`])}).catch(()=>{});}}
export async function onReceipt(sock,updates){if(!isFeatureOn('receipts'))return;
  const list=Array.isArray(updates)?updates:[updates];for(const item of list){const key=item?.key||item?.messageKey;if(!key?.id)continue;const participants=item?.receipt?.userJid?[item.receipt.userJid]:item?.receipt?.readBy||item?.receipt?.participant?[item.receipt.participant]:[];const status=item?.receipt?.status||item?.status||'read';for(const p of participants){saveReceipt({remoteJid:key.remoteJid,messageId:key.id,participantJid:p,status,ts:Date.now()});saveEvent({kind:'receipt',remoteJid:key.remoteJid,refId:key.id,data:{participant:p,status}});if(!key.fromMe)continue;if(!await shouldWatch(p)&&!isOwnerJid(sock,key.remoteJid))continue;if(!okCooldown(`receipt::${key.id}::${p}::${status}`,60000))continue;await sock.sendMessage(ownerJid(sock),{text:card('✅ *MENSAGEM LIDA*',[`👤 ${who(p)}`,`💬 ${chatKind(key.remoteJid)} · ${num(key.remoteJid)}`,`🕒 ${formatDate(Date.now())}`])}).catch(()=>{});}}
}
export async function onCall(sock,events){if(!isFeatureOn('calls'))return;const list=Array.isArray(events)?events:[events];for(const c of list){if(!c)continue;const peer=c.from||c.chatId||c.peerJid||c.remoteJid||'?';const status=c.status||c.update||'unknown';if(status!=='unknown'&&!['offer','ringing','accept','reject','timeout','terminate'].includes(status))continue;const video=!!(c.isVideo||c.video);saveCall({peerJid:peer,status,video,callId:c.id||c.callId,ts:Date.now()});saveEvent({kind:'call',remoteJid:peer,refId:c.id||c.callId,data:{status,video}});if(!await shouldWatch(peer)&&!isOwnerJid(sock,peer))continue;if(!okCooldown(`call::${peer}::${status}::${c.id||c.callId}`,5000))continue;await sock.sendMessage(ownerJid(sock),{text:card(`${video?'📹':'📞'} *LIGAÇÃO*`,[`👤 ${who(peer)}`,`📡 ${({offer:'chamando',ringing:'tocando',accept:'atendida',reject:'recusada',timeout:'sem resposta',terminate:'encerrada'})[status]||status}`,`🕒 ${formatDate(Date.now())}`])}).catch(()=>{});}}

function inferDevice(msg){const raw=String(msg?.key?.participant||msg?.key?.participantAlt||msg?.key?.remoteJid||'');const device=raw.match(/:(\d+)@/i)?.[1];if(device)return `device-${device}`;const id=String(msg?.key?.id||'');if(id.includes(':'))return `device-${id.split(':')[0]}`;return 'unknown';}
export async function onDevice(sock,msg){if(!isFeatureOn('device'))return;if(msg?.key?.fromMe||!msg?.key?.remoteJid||msg.key.remoteJid==='status@broadcast')return;const jid=msg.key.participant||msg.key.remoteJid; if(!await shouldWatch(jid))return;const device=inferDevice(msg);if(device==='unknown')return;saveEvent({kind:'device.seen',remoteJid:jid,refId:msg.key.id,data:{device}});await maybeAlertDevice(sock,jid,device);}
async function maybeAlertDevice(sock,jid,device){const k=`device.last.${jid}`, prev=await import('../core/db.js').then(m=>m.dbGet(k));if(!prev){await import('../core/db.js').then(m=>m.dbSet(k,device));return;}if(prev===device)return;await import('../core/db.js').then(m=>m.dbSet(k,device));if(!okCooldown(`device::${jid}`,300000))return;await sock.sendMessage(ownerJid(sock),{text:card('📱 *MUDANÇA DE DISPOSITIVO*',[`👤 ${who(jid)}`,`Antes: ${prev}`,`Agora: ${device}`,`🕒 ${formatDate(Date.now())}`])}).catch(()=>{});}
export function maybeSmartAlert(sock,msg){if(!isFeatureOn('smart'))return;if(!msg?.key?.remoteJid||msg.key.fromMe)return;const jid=msg.key.participant||msg.key.remoteJid;if(!watched(jid))return;const h=new Date().getHours();const set=settings(jid)||{};const allowed=set.alertHours;if(!Array.isArray(allowed)||!allowed.length)return;if(allowed.includes(h))return;if(!okCooldown(`smart::${jid}`,1800000))return;sock.sendMessage(ownerJid(sock),{text:card('🚨 *ATIVIDADE FORA DO PADRÃO*',[`👤 ${who(jid)}`,`🕒 ${formatDate(msg.messageTimestamp)}`],{body:'O horário atual não está nos horários esperados deste alvo.'})}).catch(()=>{});}
