import process from 'node:process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Carrega o .env (não sobrescreve variáveis já definidas no ambiente).
try { process.loadEnvFile?.(path.join(path.resolve(process.env.BOT_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')), '.env')); } catch { /* .env é opcional */ }

const ROOT = path.resolve(process.env.BOT_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..'));
const bool = (v, fallback) => v == null ? fallback : /^(1|true|on|yes)$/i.test(String(v));
const num = (v, fallback) => Number.isFinite(Number(v)) ? Number(v) : fallback;

export const CONFIG = Object.freeze({
  ROOT,
  BRAND: process.env.BOT_BRAND ?? 'by 𝖒𝖔𝖓𝖙𝖝2_',
  PREFIX: process.env.BOT_PREFIX || '.',
  TZ: process.env.BOT_TZ || 'America/Sao_Paulo',
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  NODE_MIN: 24,
  WA_VERSION_OVERRIDE: process.env.WA_VERSION_OVERRIDE || '',
  DEFAULT_QUERY_TIMEOUT_MS: num(process.env.DEFAULT_QUERY_TIMEOUT_MS, 60_000),
  CONNECT_TIMEOUT_MS: num(process.env.CONNECT_TIMEOUT_MS, 30_000),
  KEEP_ALIVE_INTERVAL_MS: num(process.env.KEEP_ALIVE_INTERVAL_MS, 25_000),
  RETRY_REQUEST_DELAY_MS: num(process.env.RETRY_REQUEST_DELAY_MS, 1_000),
  HEALTH_PROBE_INTERVAL_MS: num(process.env.HEALTH_PROBE_INTERVAL_MS, 5 * 60_000),
  HEALTH_PROBE_TIMEOUT_MS: num(process.env.HEALTH_PROBE_TIMEOUT_MS, 20_000),
  AUTH_DIR: path.join(ROOT, 'data', 'auth'),
  DATA_DIR: path.join(ROOT, 'data'),
  DB_PATH: path.join(ROOT, 'data', 'bot.db'),
  LOG_DIR: path.join(ROOT, 'logs'),
  STORAGE_DIR: path.join(ROOT, 'storage'),
  MEDIA_DIR: path.join(ROOT, 'storage', 'media'),
  VAULT_DIR: path.join(ROOT, 'storage', 'vault'),
  BLACK_DIR: path.join(ROOT, 'storage', 'black'),
  STATUS_DIR: path.join(ROOT, 'storage', 'status'),
  EXPORT_DIR: path.join(ROOT, 'storage', 'exports'),
  BACKUP_DIR: path.join(ROOT, 'storage', 'backups'),
  TMP_DIR: path.join(ROOT, '.tmp'),
  VIEW_ONCE_AUTO: bool(process.env.VIEW_ONCE_AUTO, true),
  VIEW_ONCE_RETRIES: num(process.env.VIEW_ONCE_RETRIES, 15),
  STATUS_SAVER: bool(process.env.STATUS_SAVER, false),
  STATUS_ONLY_WATCH: bool(process.env.STATUS_ONLY_WATCH, true),
  MEDIA_VAULT: bool(process.env.MEDIA_VAULT, true),
  MEDIA_ONLY_WATCH: bool(process.env.MEDIA_ONLY_WATCH, false),
  ANTI_DELETE: bool(process.env.ANTI_DELETE, true),
  ANTI_EDIT: bool(process.env.ANTI_EDIT, true),
  REACTION_MONITOR: bool(process.env.REACTION_MONITOR, true),
  PRESENCE_MONITOR: bool(process.env.PRESENCE_MONITOR, true),
  READ_RECEIPT_MONITOR: bool(process.env.READ_RECEIPT_MONITOR, true),
  CALL_MONITOR: bool(process.env.CALL_MONITOR, true),
  GROUP_RADAR: bool(process.env.GROUP_RADAR, true),
  FORWARD_MONITOR: bool(process.env.FORWARD_MONITOR, true),
  DEVICE_MONITOR: bool(process.env.DEVICE_MONITOR, true),
  SMART_ALERTS: bool(process.env.SMART_ALERTS, true),
  PROFILE_MONITOR: bool(process.env.PROFILE_MONITOR, false),
  AUTO_ARCHIVE: bool(process.env.AUTO_ARCHIVE, true),
  AUTO_EVENTS: bool(process.env.AUTO_EVENTS, true),
  DEFAULT_STICKER: bool(process.env.STICKER_DEFAULT, true),
  MARK_ONLINE: bool(process.env.MARK_ONLINE, false),
  MAX_MEDIA_MB: num(process.env.MAX_MEDIA_MB, 80),
  KEEP_RAW_DAYS: num(process.env.KEEP_RAW_DAYS, 21),
  MEDIA_KEEP_DAYS: num(process.env.MEDIA_KEEP_DAYS, 30),
  MEDIA_MAX_GB: num(process.env.MEDIA_MAX_GB, 4),
  LOG_MAX_MB: num(process.env.LOG_MAX_MB, 10),
  MAX_EXPORT: 5000,
  STICKER_MAX_SECONDS_LIMIT: 15,
  STICKER_MAX_SECONDS: Math.min(15, Math.max(1, num(process.env.STICKER_MAX_SECONDS, 10))),
  STICKER_PACK: process.env.STICKER_PACK || 'by 𝖒𝖔𝖓𝖙𝖝2_',
  STICKER_AUTHOR: process.env.STICKER_AUTHOR || '',
  STICKER_MAX_STATIC_KB: num(process.env.STICKER_MAX_STATIC_KB, 100),
  STICKER_MAX_ANIMATED_KB: num(process.env.STICKER_MAX_ANIMATED_KB, 500),
  STICKER_REACT: bool(process.env.STICKER_REACT, true),
  STICKER_AUTO_SELF: bool(process.env.STICKER_AUTO_SELF, false),
  VIEW_ONCE_DIR: path.join(ROOT, 'storage', 'vault', 'view-once'),
});
